
pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /root/.sbt
      - /root/.ivy2
      - /root/.m2
    volumes:
      - /tmp/cache:/cache
  commons-gen-sources:
    image: maven:3.5-alpine
    commands:
      - mvn generate-sources
  commons:
    image: bigtruedata/sbt:0.13.15-2.11.8
    commands:
      - sbt clean test publishM2
    secrets: [ artifactory_url, artifactory_username, artifactory_password ]
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /root/.sbt
      - /root/.ivy2
      - /root/.m2
    volumes:
      - /tmp/cache:/cache
  artifactory:
    image: athieriot/drone-artifactory
    environment:
      - DRONE_VERSION=0.8
    group_id: org.dcs
    artifact_id: org.dcs.commons
    version: 0.5.0-SNAPSHOT
    pom: target/org.dcs.commons-0.5.0-SNAPSHOT.pom
    files:
      - target/*.jar
    force_upload: true
    secrets: [ artifactory_url, artifactory_username, artifactory_password ]
  slack:
    image: plugins/slack
    channel: cados-builds
    secrets: [ slack_webhook ]

